# Generated by Django 5.0.1 on 2024-03-29 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_orderupdates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdates',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order'),
        ),
    ]
