# Generated by Django 5.0.1 on 2024-02-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_foodid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurantId',
            field=models.CharField(default='', max_length=200),
        ),
    ]
