# Generated by Django 5.0.1 on 2024-02-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_restaurantid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='restaurantId',
            field=models.IntegerField(default=0),
        ),
    ]
