# Generated by Django 5.0.1 on 2024-03-29 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
