# Generated by Django 5.0.1 on 2024-03-29 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='some_field',
            new_name='address',
        ),
    ]
