# Generated by Django 5.0.1 on 2024-03-31 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='process',
            field=models.BooleanField(default=False),
        ),
    ]
